[build]
builder = "dockerfile"

[deploy]
startCommand = "CHECKPOINT_DISABLE=1 node node_modules/prisma/build/index.js db push && node_modules/.bin/next start -p ${PORT:-3000}"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
